begin;
-- __B2B_MIGRATION__
do $probe$ declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); actor uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); cb uuid:=gen_random_uuid(); one uuid; two uuid; foreign_company uuid; result jsonb; begin
 insert into public.organizations(id,slug,legal_name,display_name) values(a,'b2b-probe-'||a,'Fictícia B2B A','Fictícia B2B A'),(b,'b2b-probe-'||b,'Fictícia B2B B','Fictícia B2B B');
 insert into auth.users(id,email,raw_user_meta_data) values(actor,'b2b-probe-'||actor||'@example.invalid','{"full_name":"Pessoa fictícia B2B"}');
 insert into public.user_organizations(user_id,organization_id,role,accepted_at) values(actor,a,'admin',now());
 insert into public.contacts(id,organization_id,name) values(ca,a,'Contato B2B A'),(cb,b,'Contato B2B B');
 insert into public.crm_companies(organization_id,name) values(b,'Empresa B') returning id into foreign_company;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated','aal','aal1')::text,true);
 execute 'set local role authenticated';
 if exists(select 1 from public.crm_companies where organization_id=b) then raise exception 'b2b_rls_leak'; end if;
 result:=public.fn_crm_company_manage(a,'create',null,'{"name":"Empresa A","document":"ABC-123","document_type":"registro"}');one:=(result->>'company_id')::uuid;
 result:=public.fn_crm_company_manage(a,'create',null,'{"name":"Empresa A"}');two:=(result->>'company_id')::uuid;
 begin perform public.fn_crm_company_manage(a,'create',null,'{"name":"Duplicada","document":" abc-123 ","document_type":"REGISTRO"}');raise exception 'b2b_document_duplicate_allowed'; exception when unique_violation then null; end;
 update public.contacts set company_id=one where id=ca and organization_id=a;
 if not exists(select 1 from public.contacts where id=ca and company_id=one) then raise exception 'b2b_link_failed'; end if;
 begin update public.contacts set company_id=foreign_company where id=ca;raise exception 'b2b_cross_tenant_allowed';exception when foreign_key_violation then null;end;
 begin perform public.fn_crm_company_manage(a,'archive',one);raise exception 'b2b_archive_used_allowed';exception when foreign_key_violation then null;end;
 perform public.fn_crm_company_manage(a,'edit',one,'{"name":"Empresa renomeada"}');
 if not exists(select 1 from public.contacts where id=ca and company_id=one) then raise exception 'b2b_rename_unlinked'; end if;
 update public.contacts set company_id=two where id=ca;
 update public.contacts set company_id=null where id=ca;
 if not exists(select 1 from public.crm_companies where id=one and not is_archived) then raise exception 'b2b_unlink_deleted_company';end if;
 if (select jsonb_array_length(public.fn_crm_company_contact_history(a,ca)))<>3 then raise exception 'b2b_history_missing';end if;
 perform public.fn_crm_company_manage(a,'archive',one);
 begin update public.contacts set company_id=one where id=ca;raise exception 'b2b_archived_allowed';exception when foreign_key_violation then null;end;
 result:=public.fn_crm_company_command(a,'create',null,'{"name":"Criação idempotente"}',actor);
 if public.fn_crm_company_command(a,'create',null,'{"name":"Criação idempotente"}',actor) is distinct from result then raise exception 'b2b_replay_changed';end if;
 if (select count(*) from public.crm_companies where organization_id=a and name='Criação idempotente')<>1 then raise exception 'b2b_replay_duplicate';end if;
 begin perform public.fn_crm_company_command(a,'create',null,'{"name":"Outro conteúdo"}',actor);raise exception 'b2b_replay_conflict_allowed';exception when unique_violation then null;end;
 begin update public.idempotency_keys set response_body='{}' where organization_id=a and endpoint='crm-company:create';raise exception 'b2b_receipt_forgery_allowed';exception when insufficient_privilege then null;end;
 execute 'set local role postgres';
 update public.user_organizations set role='viewer' where user_id=actor and organization_id=a;
 execute 'set local role authenticated';
 begin update public.contacts set company_id=two where id=ca;raise exception 'b2b_viewer_write_allowed';exception when insufficient_privilege then null;end;
 begin perform public.fn_crm_company_manage(a,'create',null,'{"name":"Viewer proibido"}');raise exception 'b2b_viewer_manage_allowed';exception when insufficient_privilege then null;end;
end $probe$;
select jsonb_build_object('rls',true,'cardinality',true,'cross_tenant',true,'duplicate_document',true,'homonyms',true,'rename',true,'unlink',true,'history',true,'safe_archive',true,'viewer_denied',true,'rollback',true) b2b_probe;
rollback;
